url: https://harrychowjackson.github.io
baseurl: ""

# Site settings
title: Harry Jackson
email: harrychowjackson@gmail.com
description: "Robotics, electrical, and computer engineer."


# Team names, titles and social links
people:
- name: Harry Jackson
  pic: 1
  position: "A right good lad"
  social:
    - title: github
      url: http://github.com/harrychowjackson
    - title: linkedin
      url: https://www.linkedin.com/in/harry-jackson-b525738a/
    - title: facebook
      url: http://facebook.com/harrychowjackson
    - title: instagram
      url: http://instagram.com/harrychowjackson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/harrychowjackson
  - title: linkedin
    url: https://www.linkedin.com/in/harry-jackson-b525738a/
  - title: facebook
    url: http://facebook.com/harrychowjackson
  - title: instagram
    url: http://instagram.com/harrychowjackson

# Postal address (add as many lines as necessary)
address:
  - line: 2218 Schott Ct
  - line: Santa Clara, CA 95054

# Build settings
markdown: kramdown
permalink: pretty
