url: https://harrychowjackson.github.io
baseurl: ""

# Site settings
title: Harry Jackson
email: harrychowjackson@gmail.com
description: "Electrical, robotics, and computer engineer. Wow what a professional site, I'd hire this guy."


# Team names, titles and social links
people:
- name: Harry Jackson
  pic: 1
  position: Best boi
  social:
    - title: facebook
      url: # harrychowjackson
    - title: github
      url: # harrychowjackson
    - title: instagram
      url: # harrychowjackson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/harrychowjackson
  - title: facebook
    url: http://facebook.com/harrychowjackson
  - title: github
    url: http://github.com/harrychowjackson

# Postal address (add as many lines as necessary)
address:
  - line: 2218 Schott Ct
  - line: Santa Clara, CA 95054

# Build settings
markdown: kramdown
permalink: pretty
